### ISSUE TITLE
1.16 Build can't load because of missing license information

### ISSUE THREAD

**Issue by second2050** [CursedFlames/NoIncreasingRepairCost#2]
Forge 1.16 (in my case version 1.16.3 34.1.25) refuses to load the mod because of missing license information in your ``META-INF/mods.toml`` file.
This can be fixed by including the line ``license="<License here>"`` like it did in line 13 below:
```toml
# This is an example mods.toml file. It contains the data relating to the loading mods.
# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[26,)" #mandatory (26 is current forge version)
# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/CursedFlames/NoIncreasingRepairCost/issues" #optional
# A list of mods - how many allowed here is determined by the individual mod loader
license="<License here>"
[[mods]] #mandatory
# The modid of the mod
modId="noincreasingrepaircost" #mandatory
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
version="${file.jarVersion}" #mandatory
 # A display name for the mod
displayName="No Increasing Repair Cost" #mandatory
# A URL to query for updates for this mod. See the JSON update specification <here>
# updateJSONURL="http://myurl.me/" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
# displayURL="http://example.com/" #optional
# A file name (in the root of the mod JAR) containing a logo for display
# logoFile="examplemod.png" #optional
# A text field displayed in the mod UI
# credits="Thanks for this example mod goes to Java" #optional
# A text field displayed in the mod UI
authors="CursedFlames" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
Disables the increasing repair/enchant cost on items in anvils.
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.noincreasingrepaircost]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[26,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
# Here's another dependency
[[dependencies.noincreasingrepaircost]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16,1.17)"
    ordering="NONE"
    side="BOTH"

```
